# set the control character to Ctrl+Spacebar (instead of Ctrl+B)
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# split panes using | and -
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# enable mouse mode (tmux 2.1 and above)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# removing this breaks shell in tmux
set -g default-terminal "xterm-256color"
set -s escape-time 0

# use vim keybindings in copy mode
setw -g mode-keys vi

# setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi "v" send -X begin-selection
bind-key -T copy-mode-vi "y" send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi "Enter"
bind-key -T copy-mode-vi "Enter" send -X copy-pipe "reattach-to-user-namespace pbcopy"
