#! /bin/zsh

export EDITOR=$(command -v code >/dev/null 2>&1 && echo "code --wait" || echo "vim")
export PATH=$HOME/bin:$PATH
export LD_LIBRARY_PATH=$HOME/lib:$LD_LIBRARY_PATH

export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/go/bin:$PATH

export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git vi-mode)
source $ZSH/oh-my-zsh.sh

bindkey -v
export KEYTIMEOUT=1

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if command -v pyenv >/dev/null 2>&1; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init -)"
fi

if command -v bat >/dev/null 2>&1; then
    alias cat='bat --theme "Visual Studio Dark+"'
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    export DOCKER_DEFAULT_PLATFORM=linux/amd64
    PATH="/opt/homebrew/opt/make/libexec/gnubin:$PATH"
    PATH="/Volumes/data/notes/scripts:$PATH"
fi

precmd() {
    exit_status=$?
    last_command=$(fc -ln -1)
    if [ $exit_status -ne 0 ] && [[ "$last_command" == code* ]]; then
        echo "Exit status: $exit_status for cmd: '$last_command'"
        temp_file=$(mktemp)
        echo "export VSCODE_IPC_HOOK_CLI=$(lsof 2>/dev/null | grep "$USER" | grep vscode-ipc | awk '{print $(NF-1)}' | head -n 1)" > "$temp_file"
        cat "$temp_file"
        source "$temp_file"
        rm "$temp_file"
        eval "$last_command"
    fi
}

fpath+=($HOME/.zsh/pure)

autoload -U promptinit; promptinit
prompt pure
